import type { Metadata } from "next";
import React from "react";
import { ThemeProvider } from "@mui/material/styles";
import StyledComponentsRegistry from "../../lib/registry";

import "react-lite-youtube-embed/dist/LiteYouTubeEmbed.css";
import "./global.css";
import theme from "../../theme";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider theme={theme}>
          <StyledComponentsRegistry>
            <Header></Header>
            {children}
            <Footer></Footer>
          </StyledComponentsRegistry>
        </ThemeProvider>
      </body>
    </html>
  );
}
