import type { Metadata } from "next";
import React from "react";
import StyledComponentsRegistry from "../../lib/registry";
import { GlobalStylesProvider } from "@/components/GlobalStylesProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>{/*<GlobalStylesProvider></GlobalStylesProvider>*/}</head>
      <body>
        <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
      </body>
    </html>
  );
}
